// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: forms.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createForm = `-- name: CreateForm :exec
INSERT INTO core.forms (user_id,title,description,fields,published)
VALUES ($1,$2,$3,$4,$5)
`

type CreateFormParams struct {
	UserID      uuid.UUID       `json:"user_id"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Fields      json.RawMessage `json:"fields"`
	Published   bool            `json:"published"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) error {
	_, err := q.db.Exec(ctx, createForm,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Fields,
		arg.Published,
	)
	return err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM core.forms WHERE id=$1
`

func (q *Queries) DeleteForm(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteForm, id)
	return err
}

const getForm = `-- name: GetForm :one
SELECT id, user_id, title, description, fields, published, created_at, updated_at
FROM core.forms
WHERE id = $1
`

func (q *Queries) GetForm(ctx context.Context, id uuid.UUID) (Form, error) {
	row := q.db.QueryRow(ctx, getForm, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Fields,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFormsForUser = `-- name: ListFormsForUser :many
SELECT
    id,
    user_id,
    title,
    description,
    published,
    created_at,
    updated_at
FROM core.forms
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListFormsForUserRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Published   bool               `json:"published"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListFormsForUser(ctx context.Context, userID uuid.UUID) ([]ListFormsForUserRow, error) {
	rows, err := q.db.Query(ctx, listFormsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFormsForUserRow{}
	for rows.Next() {
		var i ListFormsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :execrows
UPDATE core.forms
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    fields = COALESCE($3, fields),
    published = COALESCE($4, published)
WHERE id = $5
`

type UpdateFormParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Fields      []byte      `json:"fields"`
	Published   pgtype.Bool `json:"published"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateForm,
		arg.Title,
		arg.Description,
		arg.Fields,
		arg.Published,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
