// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateForm(ctx context.Context, arg CreateFormParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteFormsByOwner(ctx context.Context, arg DeleteFormsByOwnerParams) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	// -- name: GetFormWithSettings :one
	// SELECT
	//     f.id,
	//     f.user_id,
	//     f.title,
	//     f.description,
	//     f.fields,
	//     f.view_count,
	//     f.published,
	//     f.created_at,
	//     f.updated_at,
	//     sqlc.embed(s)
	// FROM core.forms as f
	// JOIN core.form_settings as s
	// ON f.settings_id = s.id
	// WHERE f.id = $1;
	ListFormsForUser(ctx context.Context, userID uuid.UUID) ([]ListFormsForUserRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateForm(ctx context.Context, arg UpdateFormParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
