// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO core.users (id,is_verified,created_at) VALUES ($1,$2,$3)
`

type CreateUserParams struct {
	ID         string             `json:"id"`
	IsVerified bool               `json:"is_verified"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.IsVerified, arg.CreatedAt)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM core.users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, is_verified, created_at, updated_at FROM core.users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE core.users
SET
    is_verified = COALESCE($1, is_verified)
WHERE id = $2
`

type UpdateUserParams struct {
	IsVerified pgtype.Bool `json:"is_verified"`
	ID         string      `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser, arg.IsVerified, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
