// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Form struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	Description pgtype.Text
	Fields      json.RawMessage
	ViewCount   int64
	Published   bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SettingsID  int16
}

type FormResponses struct {
	ID        uuid.UUID
	FormID    uuid.UUID
	Data      json.RawMessage
	CreatedAt pgtype.Timestamptz
}

type FormSettings struct {
	ID              int16
	BackgroundColor string
	ForegroundColor string
	PrimaryColor    string
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	Email       string
	Name        string
	PhoneNumber string
	IsVerified  bool
	AvatarUrl   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
