// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Form struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Fields      []byte             `json:"fields"`
	ViewCount   int64              `json:"view_count"`
	Published   bool               `json:"published"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SettingsID  pgtype.Int2        `json:"settings_id"`
}

type FormResponses struct {
	ID        pgtype.UUID        `json:"id"`
	FormID    pgtype.UUID        `json:"form_id"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FormSettings struct {
	ID              int16              `json:"id"`
	BackgroundColor string             `json:"background_color"`
	ForegroundColor string             `json:"foreground_color"`
	PrimaryColor    string             `json:"primary_color"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	PhoneNumber string             `json:"phone_number"`
	IsVerified  bool               `json:"is_verified"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
