// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetFormWithSettings(ctx context.Context, id pgtype.UUID) (GetFormWithSettingsRow, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	ListFormsForUser(ctx context.Context, userID pgtype.UUID) ([]ListFormsForUserRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
